// 报表工具数据集合

// 报表工具的tab选项卡列表数据
export const replaceTabList = [
  {
    label: '项目整体',
    id: 'projectReport',
  },
  {
    label: '项目阶段检查',
    id: 'projectPhaseCheck',
  },
  {
    label: '项目变更',
    id: 'projectChange',
  },
  {
    label: '项目指标',
    id: 'projectIndex',
  },
  {
    label: '项目成员参与项目统计',
    id: 'projectMemberAndTotal',
  },
  {
    label: '多项目质量',
    id: 'projectQuality',
  },
  {
    label: '汇报工时跟踪',
    id: 'reportWorkHourTracking',
  },
  {
    label: '多项目流程',
    id: 'multiprojectProcess',
  },
  {
    label: '产品转阶段决策及项目验收评审项目',
    id: 'paorductTransitionDecision',
  },
  {
    label: '评审会议纪要信息',
    id: 'reviewMeetingMinutesInfo',
  },
  {
    label: '转阶段决策',
    id: 'transitionDecision',
  },
  {
    label: '薪酬包成员替换',
    id: 'payPackeyMemberReplace',
  },
  {
    label: '薪酬包成员替换记录查询',
    id: 'payPackeyMemberReplaceRecord',
  },
  {
    label: '项目预警查询',
    id: 'projectWarningQuery',
  },
];

// 不同tab对应筛选条件的集合
export const filterList = {
  // 项目整体
  projectReport: [
    {
      items: [
        {
          label: '项目编号/名称',
          name: 'projectKeyword',
          row: 1,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'INPUT',
          displayValue: '',
        },
        {
          label: '项目立项时间',
          name: 'projectStartDate', // 开始时间 projectStartDateFrom， 结束时间 projectStartDateTo
          row: 1,
          col: 1,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'DATERANGE',
          displayValue: '',
        },
        {
          options: [],
          label: '项目类型',
          name: 'projectType',
          row: 2,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
        {
          options: [],
          label: '项目等级',
          name: 'projectLevel',
          row: 2,
          col: 1,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
        {
          options: [],
          label: '一级部门',
          name: 'primaryDepartment',
          row: 3,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
        {
          options: [],
          label: '二级部门',
          name: 'secondaryDepartment',
          row: 3,
          col: 1,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
        {
          options: [
            {
              label: '未发放',
              value: '未发放',
            },
            {
              label: '已发放',
              value: '已发放',
            },
          ],
          label: '是否发放',
          name: 'isGiven',
          row: 4,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
        {
          options: [],
          label: '评价完成时间',
          name: 'evaluationCompletionDate', // 开始时间 evaluationCompletionDateFrom，结束时间 evaluationCompletionDateTo
          row: 4,
          col: 1,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'DATERANGE',
          displayValue: '',
        },
        {
          options: [
            {
              label: '不包含',
              value: '不包含',
            },
            {
              label: '包含',
              value: '包含',
            },
          ],
          label: '是否包含没有评价的项目',
          name: 'isIncludeProjectWithNoEvaluation',
          row: 5,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
        {
          options: [],
          label: '发放时间',
          name: 'evaluationGivenDate', //开始时间 evaluationGivenDateFrom   结束时间 evaluationGivenDateTo
          row: 5,
          col: 1,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'DATERANGE',
          displayValue: '',
        },
        {
          options: [],
          label: '评价状态',
          name: 'evaluationState',
          row: 6,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: true,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
      ],
    },
  ],
  // 项目阶段检查
  projectPhaseCheck: [
    {
      items: [
        {
          options: [],
          label: '项目类型',
          name: 'projectType',
          row: 1,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
        {
          options: [],
          label: '项目阶段',
          name: 'projectPhase',
          row: 1,
          col: 1,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
        {
          options: [],
          label: '一级部门',
          name: 'primaryDepartment',
          row: 2,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
        {
          options: [],
          label: '二级部门',
          name: 'secondaryDepartment',
          row: 2,
          col: 1,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
        {
          label: '项目立项时间',
          name: 'projectStartDateFrom', // 开始时间 projectStartDateFrom   结束时间 projectStartDateTo
          row: 3,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'DATERANGE',
          displayValue: '',
        },
        {
          label: '项目名称',
          name: 'projectName',
          row: 3,
          col: 1,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'INPUT',
          displayValue: '',
        },
        {
          label: '项目编号',
          name: 'projectNumber',
          row: 4,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'INPUT',
          displayValue: '',
        },
        {
          options: [],
          label: '项目状态',
          name: 'projectState',
          row: 4,
          col: 1,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
      ],
    },
  ],
  // 项目变更
  projectChange: [
    {
      items: [
        {
          options: [],
          label: '项目类型',
          name: 'projectType',
          row: 1,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
        {
          options: [],
          label: '项目阶段',
          name: 'projectPhase',
          row: 1,
          col: 1,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
        {
          options: [],
          label: '一级部门',
          name: 'primaryDepartment',
          row: 2,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
        {
          options: [],
          label: '二级部门',
          name: 'secondaryDepartment',
          row: 2,
          col: 1,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
        {
          label: '项目立项时间',
          name: 'projectStartDateRange', // 开始时间 projectStartDateFrom   结束时间 projectStartDateTo
          row: 3,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'DATERANGE',
          displayValue: '',
        },
        {
          label: '项目名称',
          name: 'projectName',
          row: 3,
          col: 1,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'INPUT',
          displayValue: '',
        },
        {
          label: '项目编号',
          name: 'projectNumber',
          row: 4,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'INPUT',
          displayValue: '',
        },
        {
          options: [],
          label: '项目状态',
          name: 'projectState',
          row: 4,
          col: 1,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
        {
          options: [],
          label: '变更类型',
          name: 'projectChangeType',
          row: 5,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
        {
          options: [],
          label: '变更状态',
          name: 'projectChangeState',
          row: 5,
          col: 1,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
        {
          options: [],
          label: '变更所属阶段',
          name: 'projectChangePhase',
          row: 6,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
        {
          options: [],
          label: '变更日期',
          name: 'projectChangeDateFrom', //  开始日期  projectChangeDateFrom，结束日期 projectChangeDateTo;
          row: 6,
          col: 1,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'DATE',
          displayValue: '',
        },
      ],
    },
  ],
  // 项目指标
  projectIndex: [
    {
      items: [
        {
          options: [],
          label: '项目类型',
          name: 'projectType',
          row: 1,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
        {
          options: [],
          label: '当前阶段',
          name: 'projectPhase',
          row: 1,
          col: 1,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
        {
          options: [],
          label: '一级部门',
          name: 'primaryDepartment',
          row: 2,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
        {
          options: [],
          label: '二级部门',
          name: 'secondaryDepartment',
          row: 2,
          col: 1,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
        {
          label: '项目立项时间',
          name: 'projectStartDate', // 开始时间 projectStartDateFrom   结束时间 projectStartDateTo
          row: 3,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'DATERANGE',
          displayValue: '',
        },
        {
          label: '项目名称',
          name: 'projectName',
          row: 3,
          col: 1,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'INPUT',
          displayValue: '',
        },
        {
          label: '项目编号',
          name: 'projectNumber',
          row: 4,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'INPUT',
          displayValue: '',
        },
        {
          options: [],
          label: '项目状态',
          name: 'projectState',
          row: 4,
          col: 1,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
        {
          options: [],
          label: '指标类别',
          name: 'indicatorType',
          row: 5,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
      ],
    },
  ],
  // 项目成员参与项目统计报表
  projectMemberAndTotal: [
    {
      items: [
        {
          options: [],
          label: '项目类型',
          name: 'projectType',
          row: 1,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
        {
          options: [],
          label: '项目当前阶段',
          name: 'projectPhase',
          row: 1,
          col: 1,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
        {
          options: [],
          label: '一级部门',
          name: 'primaryDepartment',
          row: 2,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
        {
          options: [],
          label: '二级部门',
          name: 'secondaryDepartment',
          row: 2,
          col: 1,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
        {
          label: '项目立项时间',
          name: 'projectStartDate', // 开始时间 projectStartDateFrom   结束时间 projectStartDateTo
          row: 3,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'DATERANGE',
          displayValue: '',
        },
        {
          label: '项目名称',
          name: 'projectName',
          row: 3,
          col: 1,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'INPUT',
          displayValue: '',
        },
        {
          label: '项目编号',
          name: 'projectNumber',
          row: 4,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'INPUT',
          displayValue: '',
        },
        {
          options: [],
          label: '项目状态',
          name: 'projectState',
          row: 4,
          col: 1,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
        {
          options: [],
          label: '姓名',
          name: 'userName',
          row: 5,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'INPUT',
          displayValue: '',
        },
        {
          options: [
            {
              label: '项目经理',
              value: '项目经理',
            },
            {
              label: '核心成员',
              value: '核心成员',
            },
            {
              label: '一般成员',
              value: '一般成员',
            },
            {
              label: '支持成员',
              value: '支持成员',
            },
            {
              label: '其他',
              value: '其他',
            },
          ],
          label: '按成员角色',
          name: 'userRole',
          row: 5,
          col: 1,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
      ],
    },
  ],
  // 汇报工时跟踪
  reportWorkHourTracking: [
    {
      items: [
        {
          options: [],
          label: '一级部门',
          name: 'primaryDepartment',
          row: 1,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
        {
          options: [],
          label: '二级部门',
          name: 'secondaryDepartment',
          row: 1,
          col: 1,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
        // {
        //   options: [],
        //   label: '人员',
        //   name: 'members',
        //   row: 2,
        //   col: 0,
        //   value: '',
        //   dataType: 'java.lang.String',
        //   required: false,
        //   single: true,
        //   readOnly: false,
        //   filedType: 'select',
        //   displayValue: '',
        // },
        {
          label: '汇报时间',
          name: 'submit', // 开始时间 submitStartDate;   结束时间 submitEndDate;
          row: 2,
          col: 1,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'DATERANGE',
          displayValue: '',
        },
      ],
    },
  ],
  // 多项目流程报表
  multiprojectProcess: [
    {
      items: [
        {
          options: [],
          label: '项目类型',
          name: 'projectType',
          row: 1,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
        {
          options: [],
          label: '项目状态',
          name: 'projectState',
          row: 1,
          col: 1,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
        {
          options: [],
          label: '产品类别',
          name: 'productCategory',
          row: 2,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
        {
          label: '项目年度',
          name: 'projectStartYear',
          row: 2,
          col: 1,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'YEAR',
          displayValue: '',
        },
        {
          label: '项目编号',
          name: 'projectNumber',
          row: 3,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'INPUT',
          displayValue: '',
        },
        {
          label: '项目名称',
          name: 'projectName',
          row: 3,
          col: 1,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'INPUT',
          displayValue: '',
        },
        {
          options: [
            {
              label: '全部',
              value: 'ALL',
            },
            {
              label: '立项流程',
              value: '立项流程',
            },
            {
              label: '定级流程',
              value: '定级流程',
            },
            {
              label: '变更流程',
              value: '变更流程',
            },
            {
              label: '评审流程',
              value: '评审流程',
            },
            {
              label: '评价流程',
              value: '评价流程',
            },
            {
              label: '问题流程',
              value: '问题流程',
            },
            {
              label: '风险流程',
              value: '风险流程',
            },
          ],
          label: '流程类型',
          name: 'projectWorkflowType',
          row: 4,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
        {
          options: [
            {
              label: '全部',
              value: 'ALL',
            },
            {
              label: '打开',
              value: 'OPEN',
            },
            {
              label: '已完成',
              value: 'COMPLETED',
            },
          ],
          label: '流程状态',
          name: 'projectWorkflowState',
          row: 4,
          col: 1,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
        {
          label: '项目发起时间',
          name: 'projectWorkflowStartDate', // 开始时间 projectWorkflowStartDate   结束时间 projectWorkflowEndDate
          row: 5,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'DATERANGE',
          displayValue: '',
        },
      ],
    },
  ],
  // 项目预警查询
  projectWarningQuery: [
    {
      items: [
        {
          options: [],
          label: '项目类型',
          name: 'projectType',
          row: 1,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
        {
          options: [],
          label: '产品类别',
          name: 'productCategory',
          row: 1,
          col: 1,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
        {
          label: '项目编号',
          name: 'projectNumber',
          row: 2,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'INPUT',
          displayValue: '',
        },
        {
          label: '项目名称',
          name: 'projectName',
          row: 2,
          col: 1,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'INPUT',
          displayValue: '',
        },
        {
          label: '开始/结束日期',
          name: 'startDate', // 开始日期 startDate   结束日期 endDate
          row: 3,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'DATERANGE',
          displayValue: '',
        },
        {
          options: [],
          label: '项目状态',
          name: 'projectState',
          row: 3,
          col: 1,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
        {
          label: '项目年度',
          name: 'projectStartYear',
          row: 4,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'YEAR',
          displayValue: '',
        },
        {
          options: [],
          label: '一级部门',
          name: 'primaryDepartment',
          row: 4,
          col: 1,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
        {
          options: [],
          label: '二级部门',
          name: 'secondaryDepartment',
          row: 5,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
        {
          label: '预警天数',
          name: 'warnDays',
          row: 5,
          col: 1,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'INPUT',
          displayValue: '',
        },
        {
          label: '预警日期',
          name: 'warnDate',
          row: 6,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'DATE',
          displayValue: '',
        },
      ],
    },
  ],
  // 转阶段决策
  transitionDecision: [
    {
      items: [
        {
          label: '项目编号',
          name: 'projectNumber',
          row: 1,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'INPUT',
          displayValue: '',
        },
        {
          label: '项目名称',
          name: 'projectName',
          row: 1,
          col: 1,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'INPUT',
          displayValue: '',
        },
        {
          label: '订货号',
          name: 'productOrderNumber',
          row: 2,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'INPUT',
          displayValue: '',
        },
        {
          options: [],
          label: '项目负责人',
          name: 'projectPrincipal',
          row: 2,
          col: 1,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
        {
          label: '开始/结束日期',
          name: 'startDate', // 开始日期 startDate   结束日期 endDate
          row: 3,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'DATERANGE',
          displayValue: '',
        },
      ],
    },
  ],
  // 评审会议纪要信息
  reviewMeetingMinutesInfo: [
    {
      items: [
        {
          options: [
            {
              label: '是',
              value: '是',
            },
            {
              label: '否',
              value: '否',
            },
          ],
          label: '是否结项',
          name: 'WhetherJunction',
          row: 1,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'RADIO',
          displayValue: '',
        },
        {
          label: '项目编号',
          name: 'projectNumber',
          row: 1,
          col: 1,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'INPUT',
          displayValue: '',
        },
        {
          label: '项目名称',
          name: 'projectName',
          row: 2,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'INPUT',
          displayValue: '',
        },
        {
          options: [],
          label: '机型',
          name: 'modelType',
          row: 2,
          col: 1,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
        {
          label: '订货号',
          name: 'productOrderNumber',
          row: 3,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'INPUT',
          displayValue: '',
        },
        {
          options: [],
          label: '项目负责人',
          name: 'projectPrincipal',
          row: 3,
          col: 1,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
        {
          label: '会议纪要编号',
          name: 'meetingMinutesNumber',
          row: 4,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'INPUT',
          displayValue: '',
        },
      ],
    },
  ],
  // 产品转阶段决策及项目验收评审项目
  paorductTransitionDecision: [
    {
      items: [
        {
          label: '开始/结束日期',
          name: 'startDate', // 开始日期 startDate   结束日期 endDate
          row: 1,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'DATERANGE',
          displayValue: '',
        },
        {
          options: [],
          label: '项目当前阶段',
          name: 'projectPhase',
          row: 1,
          col: 1,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
        {
          options: [],
          label: '产品类别',
          name: 'productCategory',
          row: 2,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
        {
          label: '项目编号',
          name: 'projectNumber',
          row: 2,
          col: 1,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'INPUT',
          displayValue: '',
        },
        {
          label: '项目名称',
          name: 'projectName',
          row: 3,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'INPUT',
          displayValue: '',
        },
        {
          options: [],
          label: '机型',
          name: 'modelType',
          row: 3,
          col: 1,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
        {
          label: '订货号',
          name: 'productOrderNumber',
          row: 4,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'INPUT',
          displayValue: '',
        },
        {
          options: [
            {
              label: '是',
              value: '是',
            },
            {
              label: '否',
              value: '否',
            },
          ],
          label: '是否满足',
          name: 'whetherStandard',
          row: 4,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'RADIO',
          displayValue: '',
        },
        {
          label: '评审结论',
          name: 'reviewConclusion',
          row: 5,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'INPUT',
          displayValue: '',
        },
      ],
    },
  ],
  // 多项目质量
  projectQuality: [
    {
      items: [
        {
          label: '项目类型',
          name: 'projectType',
          row: 1,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
          options: [],
        },
        {
          options: [],
          label: '当前阶段',
          name: 'projectPhase',
          row: 1,
          col: 1,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
        {
          label: '项目立项时间',
          name: 'projectStartDate', // 开始日期 projectStartDateFrom   结束日期 projectStartDateTo
          row: 2,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'DATERANGE',
          displayValue: '',
        },
        {
          options: [],
          label: '一级部门',
          name: 'primaryDepartment',
          row: 2,
          col: 1,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
        {
          options: [],
          label: '二级部门',
          name: 'secondaryDepartment',
          row: 3,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
        {
          label: '项目名称',
          name: 'projectName',
          row: 3,
          col: 1,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'INPUT',
          displayValue: '',
        },
        {
          label: '项目编号',
          name: 'projectNumber',
          row: 4,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'INPUT',
          displayValue: '',
        },
        {
          options: [],
          label: '项目状态',
          name: 'projectState',
          row: 4,
          col: 1,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
      ],
    },
  ],
  // 薪酬包成员替换
  payPackeyMemberReplace: [
    {
      items: [
        {
          options: [],
          label: '薪酬包成员',
          name: 'rewardUser',
          row: 1,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: true,
          single: true,
          readOnly: false,
          filedType: 'selectFilter',
          displayValue: '',
        },
        {
          options: [
            {
              label: '未发放',
              value: '未发放',
            },
            {
              label: '全部',
              value: '全部',
            },
          ],
          label: '发放状态',
          name: 'publishStatus',
          row: 1,
          col: 1,
          value: '',
          dataType: 'java.lang.String',
          required: true,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
        {
          options: [],
          label: '项目类型',
          name: 'projectType',
          row: 2,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: true,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
      ],
    },
  ],
  // 薪酬包成员替换记录
  payPackeyMemberReplaceRecord: [
    {
      items: [
        {
          label: '时间范围',
          name: 'payPacketMember',
          row: 1,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'DATERANGE',
          displayValue: '',
        },
        {
          options: [],
          label: '替换人',
          name: 'replacePerson',
          row: 1,
          col: 1,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
        {
          options: [],
          label: '被替换人',
          name: 'byReplacePerson',
          row: 2,
          col: 0,
          value: '',
          dataType: 'java.lang.String',
          required: false,
          single: true,
          readOnly: false,
          filedType: 'select',
          displayValue: '',
        },
      ],
    },
  ],
};

// 各个表头

export const reportsColumns = {
  // 项目整体
  projectReport: [
    {
      label: '项目编号',
      dataIndex: 'projectNumber',
      width: 120,
    },
    {
      label: '项目名称',
      dataIndex: 'projectName',
      width: 180,
    },
    {
      label: '项目类型',
      dataIndex: 'projectType',
    },
    {
      label: '项目经理',
      dataIndex: 'projectManager',
    },
    {
      label: '项目等级',
      dataIndex: 'projectLevel',
    },
    {
      label: '项目立项时间',
      dataIndex: 'projectStartDate',
      width: 110,
    },
    {
      label: '项目主包薪酬',
      dataIndex: 'projectReward',
      width: 110,
    },
    {
      label: '评价阶段',
      dataIndex: 'phaseName',
    },
    {
      label: '评价完成时间',
      dataIndex: 'evaluationCompletionDate',
      width: 110,
    },
    {
      label: '评价得分',
      dataIndex: 'evalScore',
    },
    {
      label: '激励比例',
      dataIndex: 'phasePercent',
    },
    {
      label: '阶段标准激励',
      dataIndex: 'phaseReward1;',
      width: 120,
    },
    {
      label: '扣减金额',
      dataIndex: 'phaseCut',
    },
    {
      label: '阶段实发总额',
      dataIndex: 'phaseReward2',
      width: 110,
    },
    {
      label: '是否发放',
      dataIndex: 'isGiven',
    },
    {
      label: '发放日期',
      dataIndex: 'givenDate',
      width: 180,
      fixed: 'right',
      scopeSlot: 'issueDate',
    },
    {
      label: '累计兑现',
      dataIndex: 'givenSum',
    },
    {
      label: '剩余金额',
      dataIndex: 'surplus',
    },
  ],
  // 项目阶段检查
  projectPhaseCheck: [
    {
      label: '项目名称',
      dataIndex: '',
    },
    {
      label: '项目编号',
      dataIndex: '',
    },
    {
      label: '一级部门',
      dataIndex: '',
    },
    {
      label: '二级部门',
      dataIndex: '',
    },
    {
      label: '项目等级',
      dataIndex: '',
    },
    {
      label: '项目状态',
      dataIndex: '',
    },
    {
      label: '计划完成时间',
      dataIndex: '',
      children: [
        {
          label: '方案确认',
          dataIndex: '',
        },
        {
          label: '详细设计/开发',
          dataIndex: '',
        },
        {
          label: '测试',
          dataIndex: '',
        },
        {
          label: '上线/产品试制',
          dataIndex: '',
        },
        {
          label: '效果跟踪',
          dataIndex: '',
        },
      ],
    },
    {
      label: '实际完成时间',
      dataIndex: '',
      children: [
        {
          label: '方案确认',
          dataIndex: '',
        },
        {
          label: '详细设计/开发',
          dataIndex: '',
        },
        {
          label: '测试',
          dataIndex: '',
        },
        {
          label: '上线/产品试制',
          dataIndex: '',
        },
        {
          label: '效果跟踪',
          dataIndex: '',
        },
      ],
    },
    {
      label: '方案确认',
      dataIndex: '',
      children: [
        {
          label: '检查日期',
          dataIndex: '',
        },
        {
          label: '检查结果',
          dataIndex: '',
        },
        {
          label: '检查考核',
          dataIndex: '',
        },
      ],
    },
    {
      label: '上线',
      dataIndex: '',
      children: [
        {
          label: '检查日期',
          dataIndex: '',
        },
        {
          label: '检查结果',
          dataIndex: '',
        },
        {
          label: '检查考核',
          dataIndex: '',
        },
      ],
    },
    {
      label: '效果跟踪',
      dataIndex: '',
      children: [
        {
          label: '检查日期',
          dataIndex: '',
        },
        {
          label: '检查结果',
          dataIndex: '',
        },
        {
          label: '检查考核',
          dataIndex: '',
        },
      ],
    },
  ],
  // 项目变更
  projectChange: [
    {
      label: '项目编号',
      dataIndex: '',
    },
    {
      label: '项目名称',
      dataIndex: '',
    },
    {
      label: '变更编码',
      dataIndex: '',
    },
    {
      label: '变更时间',
      dataIndex: '',
    },
    {
      label: '变更类型',
      dataIndex: '',
    },
  ],
  // 项目指标
  projectIndex: [
    {
      label: '项目类型',
      dataIndex: 'projectType',
    },
    {
      label: '部门',
      dataIndex: 'department',
    },
    {
      label: '项目名称',
      dataIndex: 'projectName',
    },
    {
      label: '项目经理',
      dataIndex: 'actualProjectManager',
    },
    {
      label: '指标类别',
      dataIndex: 'indicatorType',
    },
    {
      label: '指标名称',
      dataIndex: 'indicatorName',
    },
    {
      label: '实际值',
      dataIndex: 'indicatorActualVal',
    },
    {
      label: '项目立项时间',
      dataIndex: 'projectStartDate',
    },
    {
      label: '当前状态',
      dataIndex: 'state',
    },
  ],
  // 项目成员参与项目统计
  projectMemberAndTotal: [
    {
      label: '姓名',
      dataIndex: 'userName',
    },
    {
      label: '项目角色',
      dataIndex: 'userRole',
    },
    {
      label: '项目名称',
      dataIndex: 'projectName',
    },
    {
      label: '项目级别',
      dataIndex: 'projectLevel',
    },
    {
      label: '项目立项日期',
      dataIndex: 'projectStartDateFrom',
    },
    {
      label: '项目状态',
      dataIndex: 'projectState',
    },
  ],
  // 多项目质量
  projectQuality: [
    {
      label: '项目编号',
      dataIndex: 'projectNumber',
    },
    {
      label: '项目名称',
      dataIndex: 'projectName',
    },
    {
      label: '项目所属部门',
      dataIndex: 'projectDepartment',
    },
    {
      label: '项目经理',
      dataIndex: '',
    },
    {
      label: '重要度等级',
      dataIndex: 'importantLevel',
    },
    {
      label: '项目类型',
      dataIndex: 'projectType',
    },
    {
      label: '产品类别',
      dataIndex: 'productCategory',
    },
    {
      label: '主要目标市场',
      dataIndex: 'marketPosition',
    },
    {
      label: '里程碑节点',
      dataIndex: 'mileStoneNode',
    },
    {
      label: '问题总数',
      dataIndex: 'issueTotalCount',
    },
    {
      label: '关闭问题数',
      dataIndex: 'issueColsedCount',
    },
    {
      label: '问题未关闭数量',
      dataIndex: 'issueOpenCount',
    },
    {
      label: '问题完成率',
      dataIndex: 'issueOnTimeRate',
    },
    {
      label: '风险总数',
      dataIndex: 'riskTotalCount',
    },
    {
      label: '处理风险数',
      dataIndex: 'riskColsedCount',
    },
    {
      label: '风险未关闭数量',
      dataIndex: 'riskOpenCount',
    },
    {
      label: '风险完成率',
      dataIndex: 'riskOnTimeRate',
    },
  ],
  // 汇报工时跟踪
  reportWorkHourTracking: [
    {
      label: '用户',
      dataIndex: '',
    },
    {
      label: '汇报时间',
      dataIndex: '',
    },
    {
      label: '正常工时',
      dataIndex: '',
    },
    {
      label: '加班工时',
      dataIndex: '',
    },
    {
      label: '所属任务',
      dataIndex: '',
    },
    {
      label: '所属项目',
      dataIndex: '',
    },
    {
      label: '所属部门',
      dataIndex: '',
    },
  ],
  // 多项目流程
  multiprojectProcess: [
    {
      label: '项目编号',
      dataIndex: 'projectNumber',
    },
    {
      label: '项目名称',
      dataIndex: 'projectName',
    },
    {
      label: '重要度等级',
      dataIndex: 'importantLevel',
    },
    {
      label: '项目类型',
      dataIndex: 'projectType',
    },
    {
      label: '发起人',
      dataIndex: 'workflowCreator',
    },
    {
      label: '流程编码',
      dataIndex: 'workflowNumber',
    },
  ],
  // 产品转阶段决策及项目验收评审项目
  paorductTransitionDecision: [
    {
      label: '项目编号',
      dataIndex: '',
    },
    {
      label: '项目名称',
      dataIndex: '',
    },
    {
      label: '机型',
      dataIndex: '',
    },
    {
      label: '订货号',
      dataIndex: '',
    },
    {
      label: '当前阶段',
      dataIndex: '',
    },
    {
      label: '转入阶段',
      dataIndex: '',
    },
    {
      label: '验收评价',
      dataIndex: '',
    },
    {
      label: '负责人',
      dataIndex: '',
    },
    {
      label: '实际进度',
      dataIndex: '',
    },
    {
      label: '标准要求',
      dataIndex: '',
    },
  ],
  // 评审会议纪要信息
  reviewMeetingMinutesInfo: [
    {
      label: '是否结项',
      dataIndex: '',
    },
    {
      label: '项目编号',
      dataIndex: '',
    },
    {
      label: '项目名称',
      dataIndex: '',
    },
    {
      label: '机型',
      dataIndex: '',
    },
    {
      label: '订货号',
      dataIndex: '',
    },
    {
      label: '会议纪要编号',
      dataIndex: '',
      // 二级动态表头
      children: [
        {
          label: '详细设计',
          dataIndex: '',
        },
        {
          label: '样机试制',
          dataIndex: '',
        },
        {
          label: '小批验证',
          dataIndex: '',
        },
        {
          label: '批量验证',
          dataIndex: '',
        },
      ],
    },
  ],
  // 转阶段决策
  transitionDecision: [
    {
      label: '项目名称',
      dataIndex: '',
    },
    {
      label: '项目编号',
      dataIndex: '',
    },
    {
      label: '当前阶段',
      dataIndex: '',
    },
    {
      label: '转入阶段',
      dataIndex: '',
    },
    {
      label: '验收评价',
      dataIndex: '',
    },
    {
      label: '汇报人',
      dataIndex: '',
    },
  ],
  // 薪酬包成员替换 --- 主包所属项目
  mainPayPackeyMemberReplace: [
    {
      label: '',
      dataIndex: '',
      children: [
        {
          label: '人员',
          dataIndex: 'pdUserFullName',
          width: 120,
        },
        {
          label: '项目编码',
          dataIndex: 'projectShortName',
          width: 120,
        },
        {
          label: '项目名称',
          dataIndex: 'projectName',
          width: 150,
        },
        {
          label: '项目经理',
          dataIndex: 'projectManager',
          width: 130,
        },
        {
          label: '项目等级',
          dataIndex: 'projectLevel',
        },
        {
          label: '薪酬包金额(元)',
          dataIndex: 'amount',
          width: 120,
        },
      ],
    },
    {
      label: '样机建造',
      dataIndex: '',
      children: [
        {
          label: '权重(%)',
          dataIndex: 'phase1Percent',
        },
        {
          label: '分数',
          dataIndex: 'phase1Score',
        },
        {
          label: '个人加权得分',
          dataIndex: 'phase1WeightedScore',
        },
        {
          label: '个人薪酬(元)',
          dataIndex: 'phase1Reward',
        },
      ],
    },
    {
      label: '小批应用',
      dataIndex: '',
      children: [
        {
          label: '权重(%)',
          dataIndex: 'phase2Percent',
        },
        {
          label: '分数',
          dataIndex: 'phase2Score',
        },
        {
          label: '个人加权得分',
          dataIndex: 'phase2WeightedScore',
        },
        {
          label: '个人薪酬(元)',
          dataIndex: 'phase2Reward',
        },
      ],
    },
    {
      label: '批量验证',
      dataIndex: '',
      children: [
        {
          label: '权重(%)',
          dataIndex: 'phase3Percent',
        },
        {
          label: '分数',
          dataIndex: 'phase3Score',
        },
        {
          label: '个人加权得分',
          dataIndex: 'phase3WeightedScore',
        },
        {
          label: '个人薪酬(元)',
          dataIndex: 'phase3Reward',
        },
      ],
    },
  ],
  // 薪酬包成员替换 --- 配包所属项目
  payPackeyMemberReplace: [
    {
      label: '',
      dataIndex: '',
      children: [
        {
          label: '人员',
          dataIndex: 'user',
          width: 60,
        },
        {
          label: '项目编码',
          dataIndex: 'projectShortName ',
        },
        {
          label: '项目名称',
          dataIndex: 'projectName',
        },
        {
          label: '项目经理',
          dataIndex: 'ProjectManager',
        },
        {
          label: '项目等级',
          dataIndex: 'projectLevel',
        },
        {
          label: '薪酬包金额(元)',
          dataIndex: 'amount',
        },
        {
          label: '部门',
          dataIndex: 'depart',
        },
      ],
    },
    {
      label: '样机建造',
      dataIndex: '',
      children: [
        {
          label: '权重(%)',
          dataIndex: 'phase1Percent',
        },
        {
          label: '分数',
          dataIndex: 'phase1Score',
        },
        {
          label: '个人加权得分',
          dataIndex: 'phase1WeightedScore',
        },
        {
          label: '个人薪酬(元)',
          dataIndex: 'phase1Reward',
        },
      ],
    },
    {
      label: '小批应用',
      dataIndex: '',
      children: [
        {
          label: '权重(%)',
          dataIndex: 'phase2Percent',
        },
        {
          label: '分数',
          dataIndex: 'phase2Score',
        },
        {
          label: '个人加权得分',
          dataIndex: 'phase2WeightedScore',
        },
        {
          label: '个人薪酬(元)',
          dataIndex: 'phase2Reward',
        },
      ],
    },
    {
      label: '批量验证',
      dataIndex: '',
      children: [
        {
          label: '权重(%)',
          dataIndex: 'phase3Percent',
        },
        {
          label: '分数',
          dataIndex: 'phase3Score',
        },
        {
          label: '个人加权得分',
          dataIndex: 'phase3WeightedScore',
        },
        {
          label: '个人薪酬(元)',
          dataIndex: 'phase3Reward',
        },
      ],
    },
  ],
  // 薪酬包成员替换记录
  payPackeyMemberReplaceRecord: [
    {
      label: '操作时间',
      dataIndex: '',
    },
    {
      label: '操作人',
      dataIndex: '',
    },
    {
      label: '替换内容',
      dataIndex: '',
    },
    {
      label: '替换人',
      dataIndex: '',
    },
    {
      label: '被替换人',
      dataIndex: '',
    },
  ],
  // 项目预警查询
  projectWarningQuery: [
    {
      label: '项目编号',
      dataIndex: '',
    },
    {
      label: '项目名称',
      dataIndex: '',
    },
    {
      label: '综合等级',
      dataIndex: '',
    },
    {
      label: '项目经理',
      dataIndex: '',
    },
    {
      label: '一级部门',
      dataIndex: '',
    },
    {
      label: '二级部门',
      dataIndex: '',
    },
    {
      label: '项目年度',
      dataIndex: '',
    },
    {
      label: '薪酬包金额',
      dataIndex: '',
    },
    {
      label: '变更次数',
      dataIndex: '',
      children: [
        {
          label: '进度',
          dataIndex: '',
        },
        {
          label: '目标/指标',
          dataIndex: '',
        },
        {
          label: '薪酬包成员',
          dataIndex: '',
        },
        {
          label: '项目属性',
          dataIndex: '',
        },
      ],
    },
    {
      label: '变更评审意见',
      dataIndex: '',
      children: [
        {
          label: '进度',
          dataIndex: '',
        },
        {
          label: '目标/指标',
          dataIndex: '',
        },
        {
          label: '薪酬包成员',
          dataIndex: '',
        },
        {
          label: '项目属性',
          dataIndex: '',
        },
      ],
    },
    {
      label: '计划完成时间',
      dataIndex: '',
      children: [
        {
          label: '先期研究与概念研究',
          dataIndex: '',
        },
        {
          label: '详细设计',
          dataIndex: '',
        },
        {
          label: '样机试制',
          dataIndex: '',
        },
        {
          label: '可靠性验证',
          dataIndex: '',
        },
        {
          label: '小批验证',
          dataIndex: '',
        },
        {
          label: '批量验证',
          dataIndex: '',
        },
      ],
    },
    {
      label: '实际完成时间',
      dataIndex: '',
      children: [
        {
          label: '先期研究与概念研究',
          dataIndex: '',
        },
        {
          label: '详细设计',
          dataIndex: '',
        },
        {
          label: '样机试制',
          dataIndex: '',
        },
        {
          label: '可靠性验证',
          dataIndex: '',
        },
        {
          label: '小批验证',
          dataIndex: '',
        },
        {
          label: '批量验证',
          dataIndex: '',
        },
      ],
    },
  ],
};
